ALTER TABLE [dbo].[KLADR] ADD CODE_REGION varchar(2); 

GO

UPDATE [dbo].[KLADR] SET CODE_REGION = NULL;

GO

UPDATE [dbo].[KLADR] SET CODE_REGION = LEFT(CODE, 2) WHERE RIGHT(CODE, 11) = '00000000000';

GO

CREATE NONCLUSTERED INDEX [KLADR_CODE_REGION] ON [dbo].[KLADR]
(
	[CODE_REGION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




ALTER TABLE [dbo].[KLADR] ADD CODE_DISTRICT varchar(5); 

GO

UPDATE [dbo].[KLADR] SET CODE_DISTRICT = NULL;

GO

UPDATE
	[dbo].[KLADR] 
SET 
	CODE_DISTRICT = LEFT(CODE, 5),
	CODE_REGION = LEFT(CODE, 2)
WHERE 
	RIGHT(CODE, 8) = '00000000' AND CODE_REGION IS NULL;

GO

CREATE NONCLUSTERED INDEX [KLADR_CODE_DISTRICT] ON [dbo].[KLADR]
(
	CODE_REGION ASC, 
	[CODE_DISTRICT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



ALTER TABLE [dbo].[KLADR] ADD CODE_CITY varchar(8); 

GO

UPDATE [dbo].[KLADR] SET CODE_CITY = NULL;

GO

UPDATE 
	[dbo].[KLADR] 
   SET 
	CODE_CITY = LEFT(CODE, 8),
	CODE_DISTRICT = LEFT(CODE, 5)
 WHERE 
	 RIGHT(CODE, 5) = '00000' AND CODE_REGION IS NULL AND CODE_DISTRICT IS NULL;

GO

CREATE NONCLUSTERED INDEX [KLADR_CODE_CODE_DISTRICT] ON [dbo].[KLADR]
(
	CODE_DISTRICT ASC, 
	[CODE_CITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



ALTER TABLE [dbo].[KLADR] ADD CODE_LOCALITY varchar(11); 

GO

UPDATE [dbo].[KLADR] SET CODE_LOCALITY = NULL;

GO

UPDATE 
	[dbo].[KLADR] 
   SET 
	CODE_LOCALITY = LEFT(CODE, 11),
	CODE_DISTRICT = LEFT(CODE, 5),
	CODE_REGION = LEFT(CODE, 2)
 WHERE 
	RIGHT(CODE, 2) = '00' AND CODE_REGION IS NULL AND CODE_DISTRICT IS NULL AND CODE_CITY IS NULL;

GO

CREATE NONCLUSTERED INDEX [KLADR_CODE_CODE_LOCALITY] ON [dbo].[KLADR]
(
	CODE_REGION,
	CODE_CITY ASC, 
	CODE_LOCALITY ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



ALTER TABLE [dbo].[STREET] ADD CODE_REGION varchar(2); 
ALTER TABLE [dbo].[STREET] ADD CODE_QUICK varchar(11); 

GO

UPDATE 
	[dbo].[STREET] 
SET 
	CODE_REGION = NULL,
	CODE_QUICK = NULL;

GO

UPDATE 
	[dbo].[STREET] 
SET 
	CODE_REGION = LEFT(CODE, 2),
	CODE_QUICK = LEFT(CODE, 11);

GO


CREATE NONCLUSTERED INDEX [STREET_CODE_QUICK] ON [dbo].[STREET]
(
	CODE_QUICK ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DOMA] ADD CODE_QUICK varchar(15); 

GO

UPDATE 
	[dbo].[DOMA] 
SET 
	CODE_QUICK = NULL;
GO

UPDATE 
	[dbo].[DOMA] 
SET 
	CODE_QUICK = LEFT(CODE, 15);

GO

CREATE NONCLUSTERED INDEX [DOMA_CODE_QUICK] ON [dbo].[DOMA]
(
	CODE_QUICK ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO