//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsHoroshiki.BusinessServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceBusinessServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceBusinessServices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsHoroshiki.BusinessServices.ResourceBusinessServices", typeof(ResourceBusinessServices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать подтверждение пароля!.
        /// </summary>
        internal static string AccountsController_ConfirmPasswordIsNull {
            get {
                return ResourceManager.GetString("AccountsController_ConfirmPasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать статус сотрудника!.
        /// </summary>
        internal static string AccountsController_EmployeeStatusIsNull {
            get {
                return ResourceManager.GetString("AccountsController_EmployeeStatusIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статуса сотрудника для указанного ID={0} не существует!.
        /// </summary>
        internal static string AccountsController_EmployeeStatusRepositoryIsNull {
            get {
                return ResourceManager.GetString("AccountsController_EmployeeStatusRepositoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать имя!.
        /// </summary>
        internal static string AccountsController_FirstNameIsNull {
            get {
                return ResourceManager.GetString("AccountsController_FirstNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указано наличие мед. книжки, но не указана дата окончания мед. книжки!.
        /// </summary>
        internal static string AccountsController_IsHaveMedicalBookMedicalBookEnd {
            get {
                return ResourceManager.GetString("AccountsController_IsHaveMedicalBookMedicalBookEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать фамилию!.
        /// </summary>
        internal static string AccountsController_LastNameIsNull {
            get {
                return ResourceManager.GetString("AccountsController_LastNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не должен быть пустым!.
        /// </summary>
        internal static string AccountsController_PasswordIsNull {
            get {
                return ResourceManager.GetString("AccountsController_PasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля не совпадают!.
        /// </summary>
        internal static string AccountsController_PasswordNotEquals {
            get {
                return ResourceManager.GetString("AccountsController_PasswordNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать должность!.
        /// </summary>
        internal static string AccountsController_PositionIsNull {
            get {
                return ResourceManager.GetString("AccountsController_PositionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должности для указанного ID={0} не существует!.
        /// </summary>
        internal static string AccountsController_PositionRepositoryIsNull {
            get {
                return ResourceManager.GetString("AccountsController_PositionRepositoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать логин!.
        /// </summary>
        internal static string AccountsController_UserNameIsNull {
            get {
                return ResourceManager.GetString("AccountsController_UserNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден!.
        /// </summary>
        internal static string AccountsController_UserNotFound {
            get {
                return ResourceManager.GetString("AccountsController_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при обновлении пользователя!.
        /// </summary>
        internal static string AccountsController_UserUpdateError {
            get {
                return ResourceManager.GetString("AccountsController_UserUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан объект для сохранения!.
        /// </summary>
        internal static string BaseEditableService_EntityAddIsNull {
            get {
                return ResourceManager.GetString("BaseEditableService_EntityAddIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан объект для обновления!.
        /// </summary>
        internal static string BaseEditableService_EntityUpdateIsNull {
            get {
                return ResourceManager.GetString("BaseEditableService_EntityUpdateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекта с Id={0} не существует!.
        /// </summary>
        internal static string BaseEditableService_EntityUpdateNotFound {
            get {
                return ResourceManager.GetString("BaseEditableService_EntityUpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение для элемента с ключом &quot;{0}&quot; в холдере {1} не может быть заменено!.
        /// </summary>
        internal static string HolderCannotReplaceValue {
            get {
                return ResourceManager.GetString("HolderCannotReplaceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способа покупки для указанного ID={0} не существует!.
        /// </summary>
        internal static string PlatformService_BuyProcessNotFound {
            get {
                return ResourceManager.GetString("PlatformService_BuyProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статуса площадки для указанного ID={0} не существует!.
        /// </summary>
        internal static string PlatformService_PlatformStatusNotFound {
            get {
                return ResourceManager.GetString("PlatformService_PlatformStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение для указанного ID={0} не существует!.
        /// </summary>
        internal static string PlatformService_SubDivisionNotFound {
            get {
                return ResourceManager.GetString("PlatformService_SubDivisionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователя для указанного ID={0} не существует!.
        /// </summary>
        internal static string PlatformService_UserNotFound {
            get {
                return ResourceManager.GetString("PlatformService_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходмио указать способы покупки!.
        /// </summary>
        internal static string PlatformValidator_BuyProcessesIsNullModel {
            get {
                return ResourceManager.GetString("PlatformValidator_BuyProcessesIsNullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный чек должен быть больше нуля!.
        /// </summary>
        internal static string PlatformValidator_MinChecksIsNull {
            get {
                return ResourceManager.GetString("PlatformValidator_MinChecksIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать статус площадки!.
        /// </summary>
        internal static string PlatformValidator_PlatformStatusIsNullModel {
            get {
                return ResourceManager.GetString("PlatformValidator_PlatformStatusIsNullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать подразделение!.
        /// </summary>
        internal static string PlatformValidator_SubDivisionIsNullModel {
            get {
                return ResourceManager.GetString("PlatformValidator_SubDivisionIsNullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать время окончания работы!.
        /// </summary>
        internal static string PlatformValidator_TimeEndIsNullModel {
            get {
                return ResourceManager.GetString("PlatformValidator_TimeEndIsNullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать время начала работы!.
        /// </summary>
        internal static string PlatformValidator_TimeStartIsNullModel {
            get {
                return ResourceManager.GetString("PlatformValidator_TimeStartIsNullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден тип цены с Id={0}!.
        /// </summary>
        internal static string SubDivisionService_PriceTypeNotFound {
            get {
                return ResourceManager.GetString("SubDivisionService_PriceTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать тип цены!.
        /// </summary>
        internal static string SubDivisionValidator_PriceTypeIsNullModel {
            get {
                return ResourceManager.GetString("SubDivisionValidator_PriceTypeIsNullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение часового пояса! Допустимый диапазон от -12 до +12!.
        /// </summary>
        internal static string SubDivisionValidator_TimezoneInvalidPeriod {
            get {
                return ResourceManager.GetString("SubDivisionValidator_TimezoneInvalidPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать часовой пояс!.
        /// </summary>
        internal static string SubDivisionValidator_TimezoneIsNull {
            get {
                return ResourceManager.GetString("SubDivisionValidator_TimezoneIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать наименование!.
        /// </summary>
        internal static string Validator_NameIsNull {
            get {
                return ResourceManager.GetString("Validator_NameIsNull", resourceCulture);
            }
        }
    }
}
