//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsHoroshiki.BusinessServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceBusinessServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceBusinessServices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsHoroshiki.BusinessServices.ResourceBusinessServices", typeof(ResourceBusinessServices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать подтверждение пароля!.
        /// </summary>
        internal static string AccountsController_ConfirmPasswordIsNull {
            get {
                return ResourceManager.GetString("AccountsController_ConfirmPasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать статус сотрудника!.
        /// </summary>
        internal static string AccountsController_EmployeeStatusIsNull {
            get {
                return ResourceManager.GetString("AccountsController_EmployeeStatusIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статуса сотрудника для указанного ID={0} не существует!.
        /// </summary>
        internal static string AccountsController_EmployeeStatusRepositoryIsNull {
            get {
                return ResourceManager.GetString("AccountsController_EmployeeStatusRepositoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать имя!.
        /// </summary>
        internal static string AccountsController_FirstNameIsNull {
            get {
                return ResourceManager.GetString("AccountsController_FirstNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать фамилию!.
        /// </summary>
        internal static string AccountsController_LastNameIsNull {
            get {
                return ResourceManager.GetString("AccountsController_LastNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не должен быть пустым!.
        /// </summary>
        internal static string AccountsController_PasswordIsNull {
            get {
                return ResourceManager.GetString("AccountsController_PasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля не совпадают!.
        /// </summary>
        internal static string AccountsController_PasswordNotEquals {
            get {
                return ResourceManager.GetString("AccountsController_PasswordNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать должность!.
        /// </summary>
        internal static string AccountsController_PositionIsNull {
            get {
                return ResourceManager.GetString("AccountsController_PositionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должности для указанного ID={0} не существует!.
        /// </summary>
        internal static string AccountsController_PositionRepositoryIsNull {
            get {
                return ResourceManager.GetString("AccountsController_PositionRepositoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать логин!.
        /// </summary>
        internal static string AccountsController_UserNameIsNull {
            get {
                return ResourceManager.GetString("AccountsController_UserNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден!.
        /// </summary>
        internal static string AccountsController_UserNotFound {
            get {
                return ResourceManager.GetString("AccountsController_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при обновлении пользователя!.
        /// </summary>
        internal static string AccountsController_UserUpdateError {
            get {
                return ResourceManager.GetString("AccountsController_UserUpdateError", resourceCulture);
            }
        }
    }
}
